### ISSUE TITLE
How to prefill saved addresses for a customer?

### ISSUE THREAD

**Issue by dianaow** [pevey/sveltekit-stripe#1]
In the Stripe documentation, it says the Address Element can  "Prefill addresses at page load when you already have an address saved for your customer"

This does not happen using this library's AddressElement component. On page load, addressElementOptions's contact array is populated with the customer's name and address.

`<AddressElement {addressElementOptions} bind:addressContainer/>`

**Comment by pevey** [comment]
In order to pre-fill addresses, you can pass in a contacts array to the address element. Generally, you will want to save the address in your own system, not Stripe, and then pass that into the Address element. I believe it is also possible to save the customer in stripe itself and preload them by passing a customer id, but this is not used as often since you will generally need the address in your own system anyway, especially if shipping something. The element components from this package support all options on the underlying elements. Just pass them through the options object. The options input is typed, so you should get some intellisense on what options are available in your IDE if you are using typescript.
